services:
  # Backend Service
  - type: web
    name: social-capital-backend
    runtime: node
    plan: free # Note: You might need to upgrade to 'starter' to attach a disk, or use the disk pricing.
    region: singapore # Choose a region close to you
    buildCommand: cd server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DB_PATH
        value: /var/data/database.sqlite
    disk:
      name: sqlite-data
      mountPath: /var/data
      sizeGB: 1
